title: CSE 212 | Programming with Data Structures
description: 
show_downloads: false
lsi: false
safe: true
source: ./
incremental: false
highlighter: rouge
gist:
  noscript: false
theme: jekyll-theme-byui-cs
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
